### ISSUE TITLE
Prevent multiple players from accessing a turnstile

### ISSUE THREAD

**Issue by Bloodlex** [Lxmune/turnstile-renewed#2]
Hello 🙂,

The idea is, that we could allow only one player to go through a turnstile per one payment. I'm not sure, if there is a nice way to block the turnstile, after it detected, that the player who paid, has already crossed it.

With a delay (even a short one) it's still possible that more than one player could go through it. If such solution is not possible, maybe you could allow fractions in time delay, like for instance 0.5 second? It could also do a trick, but I'd prefer blocking entrance after crossing.

Best regards,
Bloodlex

**Comment by Lxmune** [comment]
I will allow decimal delay soon, it's just a variable type issue. (int -> float)

As for blocking players from getting through the gate with another player's payment, this one is going to be harder to make. I got an idea but that may be not optimized at all, since it would require to check the position of EVERY players every second. I will need to think about it.

**Comment by Lxmune** [comment]
Decimals supported in the next update. As for the rest, I will keep an eye on it.

**Comment by Bloodlex** [comment]
Sure, let's do a decimal delay. It should do a trick for now and you can change it to blocking later, maybe you come across some idea how to do it :)
